# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f06fa1a6301634f2c44e9e31ae3675703ef925309b5a6293ee1069024b75351d857153ab97d4dc165e0511d18b5129c2e0ee7c4c5abe94e8e0bd1bb4f14de4a

test:
  secret_key_base: 331e627ca26dd275e79d7bfd63e53bd9c2b7fc797d37f78d766d0e32ffece89e81011d3b30e0027e4668ab58e0282e0a0204676a392124275757894d92666ae1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
